name: CD Release Workflow

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  build_package:
    name: Build & Package Release
    uses: ./.github/workflows/_build_template.yml
    with:
      build_types: '["Release"]'
      upload_artifacts: true
      
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_package
    permissions:
      contents: write
      
    steps:
      - name: Download all release artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded files (Check PDB & Binaries)
        run: ls -R dist

      - name: Create and Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}